BestRestaurant/Models/Cuisine.cs
using System.Collections.Generic;

namespace BestRestaurant.Models
{
  public class Cuisine
  {
    public Cuisine()
    {
      this.JoinEntities = new HashSet<CuisineRestaurant>();
      
    }

    public int CuisineId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<CuisineRestaurant> JoinEntities { get; set; }
    
  }
}

BestRestaurant/Controllers/CuisinesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BestRestaurant.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurant.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly BestRestaurantContext _db;

    public CuisinesController(BestRestaurantContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      ViewBag.PageTitle = "View All Cuisines";
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.PageTitle = "New Cuisine";
      return View();
    }

    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisCuisine = _db.Cuisines
      .Include(cuisine => cuisine.JoinEntities)
      .ThenInclude(join => join.Restaurant)
      .FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    public ActionResult Edit (int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost]
    public ActionResult Edit(Cuisine cuisine)
    {
      _db.Entry(cuisine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      _db.Cuisines.Remove(thisCuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurant/Controllers/RestaurantsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BestRestaurant.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BestRestaurant.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly BestRestaurantContext _db;

    public RestaurantsController(BestRestaurantContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Restaurants.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.PageTitle = "New Restaurant";
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Restaurant restaurant, int CuisineId)
    {
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      if (CuisineId !=0)
      {
        _db.CuisineRestaurant.Add(new CuisineRestaurant() { CuisineId = CuisineId, RestaurantId = restaurant.RestaurantId});
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisRestaurant = _db.Restaurants
      .Include(restaurant => restaurant.JoinEntities)
      .ThenInclude(join => join.Cuisine)
      .FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    public ActionResult Edit(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      ViewBag.CuisineId = new SelectList(_db.Cuisines,  "CuisineId", "Name");
      return View(thisRestaurant);
    }

    [HttpPost]
    public ActionResult Edit(Restaurant restaurant, int CuisineId)
    {
      if (CuisineId !=0)
      {
        _db.CuisineRestaurant.Add(new CuisineRestaurant() { CuisineId = CuisineId, RestaurantId = restaurant.RestaurantId});
      }
      _db.Entry(restaurant).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddCuisine(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View(thisRestaurant);
    }

    [HttpPost]
    public ActionResult AddCuisine(Restaurant restaurant, int CuisineId)
  {
    if (CuisineId !=0)
    {
      _db.CuisineRestaurant.Add(new CuisineRestaurant() {CuisineId = CuisineId, RestaurantId = restaurant.RestaurantId});
    _db.SaveChanges();
    }
    return RedirectToAction("Index");

  }

    public ActionResult Delete(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpPost]
    public ActionResult DeleteCuisine (int joinId)
    {
        var joinEntry = _db.CuisineRestaurant.FirstOrDefault(entry => entry.CuisineRestaurantId == joinId);
        _db.CuisineRestaurant.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

  }
}

BestRestaurant/Views/Cuisines/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Cuisine

<div class="container">
  <div class="jumbotron text-center">
    <h4>Add a new Cuisine</h4>
  </div>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  <input type="submit" value="Add new cuisine" class="btn btn-default"/>
}
<p>@Html.ActionLink("Show all cuisines", "Index")</p>
</div>

BestRestaurant/Views/Cuisines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Cuisine

<div class="container">
  <div class="jumbotron text-center">
<h2>Are you sure you want to delete this?</h2>
  </div>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")
</div>

BestRestaurant/Views/Cuisines/Details.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Cuisine;
<div class="container">
  <div class="jumbotron text-center">
<h2>Cuisine Details</h2>
  </div>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This cuisine does not contain any restaurants</p>
}
else 
{
  <h4>restaurants the cuisine contains:</h4>
  <ul>
    @foreach (var join in Model.JoinEntities)
    {
      <li>@join.Restaurant.Name</li>
    }
  </ul>
}

<p>@Html.ActionLink("Add new restaurant", "Create", "Restaurants")</p>
<p>@Html.ActionLink("Edit Cuisine", "Edit", new { id = Model.CuisineId }) </p>
<p>@Html.ActionLink("Delete Cuisine", "Delete", new { id = Model.CuisineId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>
</div>

BestRestaurant/Views/Cuisines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Cuisine

<div class="container">
  <div class="jumbotron text-center">

<h2>Edit</h2>

<h4>Edit this cuisine: @Html.DisplayFor(model => model.Name)</h4>
  </div>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CuisineId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>
</div>

BestRestaurant/Views/Cuisines/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurant.Models;

<div class="container">
  <div class="jumbotron text-center">
    <h2>Cuisines</h2>
  </div>
  @if (@Model.Count == 0)
  {
    <h3>No cuisines have been added yet.</h3>
  }

  <ul>
    @foreach(Cuisine cuisine in Model)
    {
      <li>@Html.ActionLink($"{cuisine.Name}", "Details", new { id = cuisine.CuisineId })</li>
    }
  </ul>

  <p>@Html.ActionLink("Add new cuisine", "Create")</p>
  <p>@Html.ActionLink("Home", "Index", "Home")</p>
</div>